# Generated by Django 5.2.6 on 2025-10-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chit',
            name='monthly_contribution',
        ),
        migrations.AddField(
            model_name='chit',
            name='lift_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chit',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField()),
                ('lift_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('no_lift_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.chit')),
                ('lifted_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_schedules', to='core.membership')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='chit_schedule',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.chitschedule'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExternalMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slot_count', models.PositiveIntegerField(default=1)),
                ('is_organizer', models.BooleanField(default=False)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_members', to='core.chit')),
            ],
        ),
        migrations.AddField(
            model_name='chitschedule',
            name='lifted_by_external',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_schedules', to='core.externalmember'),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.externalmember'),
        ),
        migrations.AlterUniqueTogether(
            name='chitschedule',
            unique_together={('chit', 'month_number')},
        ),
    ]
