# Generated by Django 5.2.6 on 2025-10-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_chit_monthly_contribution_chit_lift_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.membership'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_member__isnull', True), ('membership__isnull', False)), models.Q(('external_member__isnull', False), ('membership__isnull', True)), _connector='OR'), name='payment_has_one_member_type'),
        ),
    ]
